[package]
name = "day16"
version = "0.1.0"
authors = ["Andrew Tribick"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.19.4"
lazy_static = "1.4"
regex = "1.4"
